package com.demo.entities;
// Generated Jan 20, 2022, 8:39:05 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "shop")
public class Contact implements java.io.Serializable {

	private Integer contactId;
	private User userByUserIdSend;
	private User userByUserIdGet;
	private String messenger;
	private Date created;

	public Contact() {
	}

	public Contact(User userByUserIdSend, User userByUserIdGet, String messenger, Date created) {
		this.userByUserIdSend = userByUserIdSend;
		this.userByUserIdGet = userByUserIdGet;
		this.messenger = messenger;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "contact_id", unique = true, nullable = false)
	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id_send", nullable = false)
	public User getUserByUserIdSend() {
		return this.userByUserIdSend;
	}

	public void setUserByUserIdSend(User userByUserIdSend) {
		this.userByUserIdSend = userByUserIdSend;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id_get", nullable = false)
	public User getUserByUserIdGet() {
		return this.userByUserIdGet;
	}

	public void setUserByUserIdGet(User userByUserIdGet) {
		this.userByUserIdGet = userByUserIdGet;
	}

	@Column(name = "messenger", nullable = false, length = 1000)
	public String getMessenger() {
		return this.messenger;
	}

	public void setMessenger(String messenger) {
		this.messenger = messenger;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
