package com.demo.entities;
// Generated Jan 20, 2022, 8:39:05 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductReview generated by hbm2java
 */
@Entity
@Table(name = "product_review", catalog = "shop")
public class ProductReview implements java.io.Serializable {

	private Integer productRivewId;
	private Product product;
	private User user;
	private int rating;
	private String coments;
	private Date created;

	public ProductReview() {
	}

	public ProductReview(Product product, User user, int rating, String coments, Date created) {
		this.product = product;
		this.user = user;
		this.rating = rating;
		this.coments = coments;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "product_rivew_id", unique = true, nullable = false)
	public Integer getProductRivewId() {
		return this.productRivewId;
	}

	public void setProductRivewId(Integer productRivewId) {
		this.productRivewId = productRivewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "rating", nullable = false)
	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	@Column(name = "coments", nullable = false, length = 500)
	public String getComents() {
		return this.coments;
	}

	public void setComents(String coments) {
		this.coments = coments;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
