package com.demo.entities;
// Generated Jan 20, 2022, 8:39:05 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shippers generated by hbm2java
 */
@Entity
@Table(name = "shippers", catalog = "shop")
public class Shippers implements java.io.Serializable {

	private Integer shipperId;
	private String companyName;
	private double cost;
	private int status;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Shippers() {
	}

	public Shippers(String companyName, double cost, int status) {
		this.companyName = companyName;
		this.cost = cost;
		this.status = status;
	}

	public Shippers(String companyName, double cost, int status, Set<Orders> orderses) {
		this.companyName = companyName;
		this.cost = cost;
		this.status = status;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shipper_id", unique = true, nullable = false)
	public Integer getShipperId() {
		return this.shipperId;
	}

	public void setShipperId(Integer shipperId) {
		this.shipperId = shipperId;
	}

	@Column(name = "company_name", nullable = false, length = 250)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "cost", nullable = false, precision = 22, scale = 0)
	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shippers")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
